import type { BookDoc } from '../repositories/book.repository.js';

export const SEED_BOOKS: Omit<BookDoc, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Walden; or, Life in the Woods',
    authors: ['Henry David Thoreau'],
    description: 'A reflection upon simple living in natural surroundings, personal independence, and spiritual discovery away from modern hurry.',
    genres: ['Nature', 'Philosophy', 'Memoir'],
    themes: ['solitude', 'nature', 'simplicity', 'self-reliance'],
    language: 'en',
    pageCount: 352,
    publicationYear: 1854,
    difficultyScore: 7,
    publicDomain: true,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { openLibraryId: 'OL262758W' },
  },
  {
    title: 'The Call of the Wild',
    authors: ['Jack London'],
    description: 'The story of Buck, a domesticated dog snatched from his pastoral home and thrust into the wild Alaskan wilderness.',
    genres: ['Adventure', 'Fiction', 'Classics'],
    themes: ['wilderness', 'survival', 'instinct', 'freedom'],
    language: 'en',
    pageCount: 172,
    publicationYear: 1903,
    difficultyScore: 5,
    publicDomain: true,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8315124-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { openLibraryId: 'OL262846W' },
  },
  {
    title: 'Braiding Sweetgrass',
    subtitle: 'Indigenous Wisdom, Scientific Knowledge and the Teachings of Plants',
    authors: ['Robin Wall Kimmerer'],
    description: 'Drawing on her life as an indigenous scientist and mother, Kimmerer shows how other living beings offer us gifts and lessons.',
    genres: ['Nature', 'Science', 'Essays'],
    themes: ['ecology', 'gratitude', 'reciprocity', 'indigenous knowledge'],
    language: 'en',
    pageCount: 408,
    publicationYear: 2013,
    difficultyScore: 6,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/10523428-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9781571313560' },
  },
  {
    title: 'A Walk in the Woods',
    subtitle: 'Rediscovering America on the Appalachian Trail',
    authors: ['Bill Bryson'],
    description: 'A hilarious and insightful chronicle of walking the legendary 2,100-mile Appalachian Trail stretching from Georgia to Maine.',
    genres: ['Travel', 'Memoir', 'Humor', 'Nature'],
    themes: ['walking', 'trail', 'humor', 'wilderness'],
    language: 'en',
    pageCount: 397,
    publicationYear: 1998,
    difficultyScore: 5,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8235221-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780767902526' },
  },
  {
    title: 'The Old Man and the Sea',
    authors: ['Ernest Hemingway'],
    description: 'The heroic struggle between an aging Cuban fisherman and a giant marlin far out in the Gulf Stream.',
    genres: ['Fiction', 'Classics', 'Literary'],
    themes: ['perseverance', 'nature', 'dignity', 'courage'],
    language: 'en',
    pageCount: 128,
    publicationYear: 1952,
    difficultyScore: 4,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8225651-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780684801223' },
  },
  {
    title: 'The Mountains of California',
    authors: ['John Muir'],
    description: 'Muir’s lyrical exploration of the Sierra Nevada mountains, passes, glaciers, forests, and storms.',
    genres: ['Nature', 'Travel', 'Classics'],
    themes: ['mountains', 'conservation', 'wonder', 'exploration'],
    language: 'en',
    pageCount: 384,
    publicationYear: 1894,
    difficultyScore: 7,
    publicDomain: true,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/6520932-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { openLibraryId: 'OL262912W' },
  },
  {
    title: 'Pilgrim at Tinker Creek',
    authors: ['Annie Dillard'],
    description: 'A personal narrative of contemplation and keen observation of the natural world in Virginia’s Roanoke Valley.',
    genres: ['Nature', 'Memoir', 'Philosophy'],
    themes: ['observation', 'seasons', 'mystery', 'stillness'],
    language: 'en',
    pageCount: 288,
    publicationYear: 1974,
    difficultyScore: 7,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8233314-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780061233326' },
  },
  {
    title: 'The Hobbit',
    subtitle: 'There and Back Again',
    authors: ['J.R.R. Tolkien'],
    description: 'Bilbo Baggins is whisked away from his quiet shire into an epic quest through wild landscapes, mountains, and ancient ruins.',
    genres: ['Fantasy', 'Adventure', 'Classics'],
    themes: ['journey', 'courage', 'discovery', 'departure'],
    language: 'en',
    pageCount: 310,
    publicationYear: 1937,
    difficultyScore: 5,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8406786-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780547928227' },
  },
  {
    title: 'The Nature Fix',
    subtitle: 'Why Nature Makes Us Happier, Healthier, and More Creative',
    authors: ['Florence Williams'],
    description: 'An investigation into nature’s restorative powers on the human brain, mental health, and physical vitality.',
    genres: ['Science', 'Health', 'Nature'],
    themes: ['neuroscience', 'outdoors', 'touch grass', 'restoration'],
    language: 'en',
    pageCount: 304,
    publicationYear: 2017,
    difficultyScore: 5,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8315121-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780393242713' },
  },
  {
    title: 'Desert Solitaire',
    subtitle: 'A Season in the Wilderness',
    authors: ['Edward Abbey'],
    description: 'A passionate, witty work documenting three seasons working as a park ranger in southeastern Utah.',
    genres: ['Nature', 'Memoir', 'Environment'],
    themes: ['desert', 'solitude', 'conservation', 'adventure'],
    language: 'en',
    pageCount: 337,
    publicationYear: 1968,
    difficultyScore: 6,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8235222-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780671695880' },
  },
  {
    title: 'Around the World in Eighty Days',
    authors: ['Jules Verne'],
    description: 'Phileas Fogg embarks on an audacious journey across oceans, continents, and railways to circle the globe.',
    genres: ['Adventure', 'Classics', 'Fiction'],
    themes: ['travel', 'curiosity', 'journey', 'time'],
    language: 'en',
    pageCount: 252,
    publicationYear: 1872,
    difficultyScore: 5,
    publicDomain: true,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8226191-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { openLibraryId: 'OL262885W' },
  },
  {
    title: 'Wanderlust',
    subtitle: 'A History of Walking',
    authors: ['Rebecca Solnit'],
    description: 'A fascinating history of walking through philosophy, literature, culture, rebellion, and geography.',
    genres: ['History', 'Philosophy', 'Essays'],
    themes: ['walking', 'flâneur', 'wander', 'presence'],
    language: 'en',
    pageCount: 336,
    publicationYear: 2000,
    difficultyScore: 7,
    publicDomain: false,
    coverImageUrl: 'https://covers.openlibrary.org/b/id/8234125-L.jpg',
    source: 'seed',
    metadataQuality: 1.0,
    externalIds: { isbn13: '9780140286014' },
  },
];
